
name = "monster-clicker"
compatibility_date = "2024-04-03"
pages_build_output_dir = "."

[vars]
SUPPORT_EMAIL = "officalmonsterenergyclicker@gmail.com"
APP_VERSION = "1.0.0"

[[kv_namespaces]]
binding = "STATS_KV"
id = "xxxxxxxxxxxx" # Replace with actual ID after creation
